// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoswm3_9L7KWkYXcKzqJWjjT7n3n3lWX0',
    appId: '1:612280367220:web:123f72238bd91a6b413921',
    messagingSenderId: '612280367220',
    projectId: 'ultmatixorangeflutter',
    authDomain: 'ultmatixorangeflutter.firebaseapp.com',
    storageBucket: 'ultmatixorangeflutter.firebasestorage.app',
    measurementId: 'G-Y14T0049E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_40rPiHNRJVtjQkJ1TN6NZoehEMVX1Q',
    appId: '1:612280367220:android:a010b2bde8022b1e413921',
    messagingSenderId: '612280367220',
    projectId: 'ultmatixorangeflutter',
    storageBucket: 'ultmatixorangeflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA3zmb_fGM4HsRc_MqNI9Zlsrmokm5n20',
    appId: '1:612280367220:ios:f632947acd03c3b7413921',
    messagingSenderId: '612280367220',
    projectId: 'ultmatixorangeflutter',
    storageBucket: 'ultmatixorangeflutter.firebasestorage.app',
    iosBundleId: 'com.orange.ultmatix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA3zmb_fGM4HsRc_MqNI9Zlsrmokm5n20',
    appId: '1:612280367220:ios:1b63a4600bcdb9d7413921',
    messagingSenderId: '612280367220',
    projectId: 'ultmatixorangeflutter',
    storageBucket: 'ultmatixorangeflutter.firebasestorage.app',
    iosBundleId: 'com.orange.ultmatix.ultimatixHrmsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoswm3_9L7KWkYXcKzqJWjjT7n3n3lWX0',
    appId: '1:612280367220:web:ffb0652f024d85f0413921',
    messagingSenderId: '612280367220',
    projectId: 'ultmatixorangeflutter',
    authDomain: 'ultmatixorangeflutter.firebaseapp.com',
    storageBucket: 'ultmatixorangeflutter.firebasestorage.app',
    measurementId: 'G-TG63RN9MNE',
  );

}