// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinRedZSefV7j0UqK7mbTrMCRwZW-AIvc',
    appId: '1:113535576900:web:5749a4512cd9b691bd0511',
    messagingSenderId: '113535576900',
    projectId: 'ultimatixorange',
    authDomain: 'ultimatixorange.firebaseapp.com',
    storageBucket: 'ultimatixorange.firebasestorage.app',
    measurementId: 'G-7E1QHDJYZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCvzzp7t5HStm6UVY4FlzWbIBAqiDomg',
    appId: '1:113535576900:android:20f28a97c686b00dbd0511',
    messagingSenderId: '113535576900',
    projectId: 'ultimatixorange',
    storageBucket: 'ultimatixorange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGENsvOyCjX3DR7r9i31YE3xBaYKkRXg',
    appId: '1:113535576900:ios:6dc37664975f9cadbd0511',
    messagingSenderId: '113535576900',
    projectId: 'ultimatixorange',
    storageBucket: 'ultimatixorange.firebasestorage.app',
    iosBundleId: 'com.ultmatix.orange.ultimatixHrmsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGENsvOyCjX3DR7r9i31YE3xBaYKkRXg',
    appId: '1:113535576900:ios:6dc37664975f9cadbd0511',
    messagingSenderId: '113535576900',
    projectId: 'ultimatixorange',
    storageBucket: 'ultimatixorange.firebasestorage.app',
    iosBundleId: 'com.ultmatix.orange.ultimatixHrmsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinRedZSefV7j0UqK7mbTrMCRwZW-AIvc',
    appId: '1:113535576900:web:b77f23acb1f715edbd0511',
    messagingSenderId: '113535576900',
    projectId: 'ultimatixorange',
    authDomain: 'ultimatixorange.firebaseapp.com',
    storageBucket: 'ultimatixorange.firebasestorage.app',
    measurementId: 'G-027B3LC1HN',
  );
}
